#Configuración de Permisos por Rol - ERP LAREDO (FR-042)
#Sun Jun 28 01:18:57 COT 2026
FINANZAS=FINANZAS,COMPRAS
ALMACENERO=INVENTARIO,COMPRAS
VENDEDOR=VENTAS
ADMINISTRADOR=VENTAS,INVENTARIO,COMPRAS,FINANZAS,PERSONAL,REPORTES,ADMINISTRACION
GERENTE=VENTAS,INVENTARIO,COMPRAS,FINANZAS,PERSONAL,REPORTES
