package Vista;

import Clases.Categoria;
import ArchivosTXT.ArchivoCategoriaTXT;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN GR
 */
public class NewCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewCategory
     */
    public NewCategory() {
        initComponents();
        this.setSize(new Dimension(500, 300));
        this.setTitle("Nueva Categoria");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripciones = new javax.swing.JTextField();
        jButton_Guardar_categoria = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nueva Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Descripcion Categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txt_descripciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_descripciones.setPreferredSize(new java.awt.Dimension(70, 30));
        txt_descripciones.addActionListener(this::txt_descripcionesActionPerformed);
        txt_descripciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcionesKeyTyped(evt);
            }
        });
        getContentPane().add(txt_descripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 30));

        jButton_Guardar_categoria.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Guardar_categoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Guardar_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Guardar_categoria.setText("Guardar");
        jButton_Guardar_categoria.addActionListener(this::jButton_Guardar_categoriaActionPerformed);
        getContentPane().add(jButton_Guardar_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionesActionPerformed

    private void jButton_Guardar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Guardar_categoriaActionPerformed
        ArchivoCategoriaTXT archivo = new ArchivoCategoriaTXT();
        List<Categoria> lista = archivo.leer();

        String descripcion = txt_descripciones.getText().trim();

        // Aqui se validara si hay un vacio o no
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una descripción");
            return;
        }

        // aqui se validara si esta duplicado o no
        for (Categoria c : lista) {
            if (c.getDescripcion().equalsIgnoreCase(descripcion)) {
                JOptionPane.showMessageDialog(this, "La categoría ya existe");
                return;
            }
        }

        // Genera la enumeracion
        int nuevoId = 1;
        if (!lista.isEmpty()) {
            nuevoId = lista.get(lista.size() - 1).getIdCategoria() + 1;

            //Busca el ID más alto (no solo el último)
            //LUEGO SE VERA SI SE CAMBIA(servira para cuando quiera eliminar)
            //int nuevoId = 1;
            //for (Categoria c : lista) {
            //if (c.getIdCategoria() >= nuevoId) {
            //nuevoId = c.getIdCategoria() + 1;
            //}
            //}
        }

        // Guarda la categoria(crea un obejto)
        Categoria nueva = new Categoria(nuevoId, descripcion, 1);

        lista.add(nueva);
        archivo.guardar(lista);

        JOptionPane.showMessageDialog(this, "Categoría guardada correctamente");

        txt_descripciones.setText("");
    }//GEN-LAST:event_jButton_Guardar_categoriaActionPerformed

    private void txt_descripcionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionesKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c)
                && c != ' '
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {

            evt.consume();

            JOptionPane.showMessageDialog(
                    this,
                    "Solo se permiten letras");
        }
    }//GEN-LAST:event_txt_descripcionesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_descripciones;
    // End of variables declaration//GEN-END:variables
}
