package Vista;

import Clases.Categoria;
import Clases.Producto;
import ArchivosTXT.ArchivoCategoriaTXT;
import ArchivosTXT.ArchivoProductoTXT;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN GR
 */
public class NewProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewProduct
     */
    public NewProduct() {
        initComponents();
        this.setSize(new Dimension(500, 400));
        this.setTitle("Nuevo Producto");

        cargarCategorias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jButton_Guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nuevo Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descripcion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio(c/u):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categorias:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 90, -1));

        txt_nombre.addActionListener(this::txt_nombreActionPerformed);
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, -1));

        txt_cantidad.addActionListener(this::txt_cantidadActionPerformed);
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 200, -1));

        txt_precio.addActionListener(this::txt_precioActionPerformed);
        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_precioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, -1));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, -1));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_categoria.addActionListener(this::jComboBox_categoriaActionPerformed);
        getContentPane().add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, -1));

        jButton_Guardar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(this::jButton_GuardarActionPerformed);
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        ArchivoProductoTXT archivo = new ArchivoProductoTXT();
        List<Producto> lista = archivo.leer();

        String nombre = txt_nombre.getText().trim();
        String cantidadTexto = txt_cantidad.getText().trim();
        String precioTexto = txt_precio.getText().trim();
        String descripcion = txt_descripcion.getText().trim();

        // Validas si los campos estan vacios menos descripcion
        if (nombre.isEmpty() || cantidadTexto.isEmpty() || precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        // Nos obliga a elegir una categoria si o si
        if (jComboBox_categoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría");
            return;
        }

        int cantidad = Integer.parseInt(cantidadTexto);
        double precio = Double.parseDouble(precioTexto);
        
        //Valida productos repetidos
        for (Producto p : lista) {

            if (p.getNombre().equalsIgnoreCase(nombre)&& p.getDescripcion().equalsIgnoreCase(descripcion)) {

                JOptionPane.showMessageDialog(this,"El producto ya existe");
                return;
            }
        }

        //OBTENEMOS EL ID DE LA CATEGORIA SELECCIONADA
        // Se obtiene el texto del ComboBox (ejemplo: "2-Abarrotes")
        // Luego se separa usando split("-") para dividir el ID y la descripción
        // Finalmente se convierte el ID (que es texto) a número entero
        String seleccion = jComboBox_categoria.getSelectedItem().toString();
        int idCategoria = Integer.parseInt(seleccion.split("-")[0]);

        //GENERA UN ID PARA EL PRODUCTO QUE SE INGRESE
        // Se inicializa el ID en 1 por si la lista está vacía
        // Luego se recorre la lista de productos existentes
        // Se busca el ID más alto y se le suma 1 para evitar duplicados
        int nuevoId = 1;
        for (Producto p : lista) {
            if (p.getIdProducto() >= nuevoId) {
                nuevoId = p.getIdProducto() + 1;
            }
        }

        Producto nuevo = new Producto(nuevoId, nombre, cantidad, precio, descripcion, idCategoria, 1);

        lista.add(nuevo);
        archivo.guardar(lista);

        JOptionPane.showMessageDialog(this, "Producto guardado correctamente");

        // Limpia los campos que tenemos en jFrame
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_descripcion.setText("");
        jComboBox_categoria.setSelectedIndex(0);
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != ' ' && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras");
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)
                && c != '.'
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números");
        }

        if (c == '.' && txt_precio.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_precioKeyTyped

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        char c = evt.getKeyChar();

        // Solo números y borrar
        if (!Character.isDigit(c)
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Agregue una cantidad valida");
        }

        // No permitir espacios
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    public void cargarCategorias() {

        ArchivoCategoriaTXT archivo = new ArchivoCategoriaTXT();
        List<Categoria> lista = archivo.leer();

        jComboBox_categoria.removeAllItems();
        jComboBox_categoria.addItem("Seleccione categoria");

        for (Categoria c : lista) {
            jComboBox_categoria.addItem(c.getIdCategoria() + "-" + c.getDescripcion());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
