package Vista;

import Clases.Cliente;
import Clases.Producto;
import Clases.Venta;
import ArchivosTXT.ArchivoClienteTXT;
import ArchivosTXT.ArchivoProductoTXT;
import ArchivosTXT.ArchivoVentaTXT;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author SEBASTIAN GR
 */
public class NewVent extends javax.swing.JInternalFrame {

    public NewVent() {
        initComponents();

        this.setSize(new Dimension(900, 700));
        this.setTitle("Nueva Venta");
        cargarClientes();
        cargarProductos();

        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {

                // Solo la columna Accion será editable
                return column == 7;
            }
        };

        modelo.addColumn("N");
        modelo.addColumn("Nombre");
        modelo.addColumn("Cantidad");
        modelo.addColumn("P. Unitario");
        modelo.addColumn("SubTotal");
        modelo.addColumn("Descuento");
        modelo.addColumn("Total Pagar");
        modelo.addColumn("Accion");

        jTable_Venta.setModel(modelo);

        jTable_Venta.getColumnModel().getColumn(7).setCellRenderer(new BotonRenderer());
        jTable_Venta.getColumnModel().getColumn(7).setCellEditor(new BotonEditor(jTable_Venta));
    }

    class BotonRenderer extends JButton implements TableCellRenderer {

        public BotonRenderer() {
            setText("Eliminar");
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {

            return this;
        }
    }

    class BotonEditor extends AbstractCellEditor implements TableCellEditor {

        private JButton button;
        private JTable table;

        public BotonEditor(JTable table) {

            this.table = table;

            button = new JButton("Eliminar");

            button.addActionListener(e -> {

                fireEditingStopped();

                DefaultTableModel modelo
                        = (DefaultTableModel) table.getModel();

                int fila = table.getSelectedRow();

                if (fila != -1) {

                    modelo.removeRow(fila);
                    calcularTotalVenta();
                    //Si ya no hay productos, habilitar cliente nuevamente
                    if (modelo.getRowCount() == 0) {
                        jComboBox_Clientes.setEnabled(true);
                    }
                    // Renumerar columna N
                    for (int i = 0; i < modelo.getRowCount(); i++) {

                        modelo.setValueAt(i + 1, i, 0);
                    }
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(
                JTable table,
                Object value,
                boolean isSelected,
                int row,
                int column) {

            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "Eliminar";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Clientes = new javax.swing.JComboBox<>();
        jTextField_BuscarDNI = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Productos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_cantidad_Elegida = new javax.swing.JTextField();
        jButton_AñadirProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Venta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Subtotal = new javax.swing.JTextField();
        jTextField_Descuento = new javax.swing.JTextField();
        jTextField_TotalPagar = new javax.swing.JTextField();
        jButton_Calc_Cambio = new javax.swing.JButton();
        txt_efectivo = new javax.swing.JTextField();
        jTextField_Cambio = new javax.swing.JTextField();
        jButton_Regis_venta = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("FACTURACION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, 30));

        jComboBox_Clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cliente:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Clientes.addActionListener(this::jComboBox_ClientesActionPerformed);
        getContentPane().add(jComboBox_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 200, 30));

        jTextField_BuscarDNI.addActionListener(this::jTextField_BuscarDNIActionPerformed);
        jTextField_BuscarDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_BuscarDNIKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_BuscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 200, 30));

        jButton_Buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(this::jButton_BuscarActionPerformed);
        getContentPane().add(jButton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        jComboBox_Productos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Producto:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Productos.addActionListener(this::jComboBox_ProductosActionPerformed);
        getContentPane().add(jComboBox_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 30));

        txt_cantidad_Elegida.addActionListener(this::txt_cantidad_ElegidaActionPerformed);
        txt_cantidad_Elegida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidad_ElegidaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad_Elegida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 60, 30));

        jButton_AñadirProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_AñadirProducto.setText("Añadir Productos");
        jButton_AñadirProducto.addActionListener(this::jButton_AñadirProductoActionPerformed);
        getContentPane().add(jButton_AñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 150, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Venta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 870, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Subtotal:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Descuento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Total a Pagar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Efectivo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        jTextField_Subtotal.setEnabled(false);
        jTextField_Subtotal.addActionListener(this::jTextField_SubtotalActionPerformed);
        jPanel2.add(jTextField_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        jTextField_Descuento.setEnabled(false);
        jPanel2.add(jTextField_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 30));

        jTextField_TotalPagar.setEnabled(false);
        jPanel2.add(jTextField_TotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jButton_Calc_Cambio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Calc_Cambio.setText("Calcular Cambio");
        jButton_Calc_Cambio.addActionListener(this::jButton_Calc_CambioActionPerformed);
        jPanel2.add(jButton_Calc_Cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, 70));

        txt_efectivo.addActionListener(this::txt_efectivoActionPerformed);
        txt_efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_efectivoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_efectivoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, 30));

        jTextField_Cambio.setEnabled(false);
        jPanel2.add(jTextField_Cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 500, 250));

        jButton_Regis_venta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Regis_venta.setText("Registrar Venta");
        jButton_Regis_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Regis_venta.addActionListener(this::jButton_Regis_ventaActionPerformed);
        getContentPane().add(jButton_Regis_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 160, 140));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed

        String dniBuscar = jTextField_BuscarDNI.getText().trim();

        if (dniBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI");
            return;
        }

        ArchivoClienteTXT archivo = new ArchivoClienteTXT();
        List<Cliente> lista = archivo.leer();

        boolean encontrado = false;

        for (Cliente c : lista) {

            if (c.getDni().equals(dniBuscar)) {

                String cliente = c.getNombre() + " " + c.getApellido();

                jComboBox_Clientes.setSelectedItem(cliente);
                jTextField_BuscarDNI.setText("");

                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado");
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void txt_cantidad_ElegidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_ElegidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_ElegidaActionPerformed

    private void jButton_AñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirProductoActionPerformed

        String clienteSeleccionado = jComboBox_Clientes.getSelectedItem().toString();

        if (clienteSeleccionado.equals("Seleccione Cliente:")) {

            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }

        String productoSeleccionado = jComboBox_Productos.getSelectedItem().toString();

        if (productoSeleccionado.equals("Seleccione Producto:")) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        if (txt_cantidad_Elegida.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad");
            return;
        }

        int cantidadElegida = Integer.parseInt(txt_cantidad_Elegida.getText());

        ArchivoProductoTXT archivo = new ArchivoProductoTXT();
        List<Producto> lista = archivo.leer();

        Producto productoEncontrado = null;

        for (Producto p : lista) {

            String nombreCombo = p.getNombre() + " (" + p.getDescripcion() + ")";

            if (nombreCombo.equals(productoSeleccionado)) {
                productoEncontrado = p;
                break;
            }
        }

        if (productoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            return;
        }

        // VALIDAR STOCK
        if (cantidadElegida > productoEncontrado.getCantidad()) {

            JOptionPane.showMessageDialog(this, "Stock insuficiente\nStock disponible: " + productoEncontrado.getCantidad());
            return;
        }

        double precio = productoEncontrado.getPrecio();
        double subtotal = cantidadElegida * precio;
        double descuento = 0;
        double total = subtotal - descuento;

        DefaultTableModel modelo = (DefaultTableModel) jTable_Venta.getModel();

        int numero = modelo.getRowCount() + 1;

        Object[] fila = {
            numero,
            productoEncontrado.getNombre(),
            cantidadElegida,
            String.format("%.2f", precio),
            String.format("%.2f", subtotal),
            String.format("%.2f", descuento),
            String.format("%.2f", total),
            "Eliminar"
        };

        modelo.addRow(fila);
        jComboBox_Clientes.setEnabled(false);
        calcularTotalVenta();
        txt_cantidad_Elegida.setText("");
    }//GEN-LAST:event_jButton_AñadirProductoActionPerformed

    private void txt_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_efectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_efectivoActionPerformed

    private void jTextField_SubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SubtotalActionPerformed

    private void jButton_Calc_CambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Calc_CambioActionPerformed

        try {

            double efectivo = Double.parseDouble(
                    txt_efectivo.getText().replace(",", "."));

            double total = Double.parseDouble(
                    jTextField_TotalPagar.getText().replace(",", "."));

            if (efectivo < total) {

                JOptionPane.showMessageDialog(this, "Efectivo insuficiente");
                return;
            }

            double cambio = efectivo - total;

            jTextField_Cambio.setText(String.format("%.2f", cambio));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Ingrese valores válidos");
        }
    }//GEN-LAST:event_jButton_Calc_CambioActionPerformed

    private void jButton_Regis_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Regis_ventaActionPerformed
        try {

            if (jTable_Venta.getRowCount() == 0) {

                JOptionPane.showMessageDialog(this,
                        "No hay productos en la venta");

                return;
            }

            // Guarda la vente en el txt
            ArchivoVentaTXT archivoVenta = new ArchivoVentaTXT();

            // Genera el id del cliente automaticamente
            int idVenta = archivoVenta.leer().size() + 1;

            // 
            String cliente = jComboBox_Clientes.getSelectedItem().toString();

            // TOTAL
            double totalVenta = Double.parseDouble(jTextField_TotalPagar.getText());

            // FECHA
            String fecha = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            // CREAR OBJETO
            Venta venta = new Venta(idVenta, cliente, totalVenta, fecha);

            // GUARDAR EN TXT
            archivoVenta.guardar(venta);

            // ACTUALIZAR STOCK
            ArchivoProductoTXT archivoProducto
                    = new ArchivoProductoTXT();

            List<Producto> listaProductos
                    = archivoProducto.leer();

            DefaultTableModel modelo
                    = (DefaultTableModel) jTable_Venta.getModel();

            for (int i = 0; i < modelo.getRowCount(); i++) {

                String nombreProducto
                        = modelo.getValueAt(i, 1).toString();

                int cantidadVendida
                        = Integer.parseInt(
                                modelo.getValueAt(i, 2).toString());

                for (Producto p : listaProductos) {

                    if (p.getNombre().equals(nombreProducto)) {

                        int nuevoStock
                                = p.getCantidad() - cantidadVendida;

                        p.setCantidad(nuevoStock);

                        break;
                    }
                }
            }

            // GUARDAR CAMBIOS
            archivoProducto.guardarLista(listaProductos);

            Document documento = new Document();

            PdfWriter.getInstance(documento,
                    new FileOutputStream("Boleta.pdf"));

            documento.open();

            // FUENTES
            Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font textoFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);

            // TITULO
            Paragraph titulo = new Paragraph("BOLETA DE VENTA", tituloFont);
            titulo.setAlignment(Element.ALIGN_CENTER);

            documento.add(titulo);
            documento.add(new Paragraph(" "));

            // DATOS EMPRESA
            documento.add(new Paragraph("MiniMarket LAREDO", headerFont));
            documento.add(new Paragraph("RUC: 20512347683", textoFont));
            documento.add(new Paragraph("Telefono: 922891674", textoFont));
            documento.add(new Paragraph("Direccion: Laredo - Peru", textoFont));

            documento.add(new Paragraph(" "));

            // DATOS CLIENTE
            documento.add(new Paragraph("DATOS DEL CLIENTE", headerFont));

            documento.add(new Paragraph("Cliente: " + jComboBox_Clientes.getSelectedItem().toString(), textoFont));

            documento.add(new Paragraph("Fecha: " + fecha, textoFont));

            documento.add(new Paragraph(" "));

            // TABLA
            PdfPTable tablaPDF = new PdfPTable(4);

            tablaPDF.setWidthPercentage(100);

            tablaPDF.setWidths(new float[]{4, 2, 2, 2});

            // ENCABEZADOS
            PdfPCell cell1 = new PdfPCell(new Phrase("Producto", headerFont));
            PdfPCell cell2 = new PdfPCell(new Phrase("Cantidad", headerFont));
            PdfPCell cell3 = new PdfPCell(new Phrase("Precio", headerFont));
            PdfPCell cell4 = new PdfPCell(new Phrase("Total", headerFont));

            cell1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell3.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell4.setBackgroundColor(BaseColor.LIGHT_GRAY);

            tablaPDF.addCell(cell1);
            tablaPDF.addCell(cell2);
            tablaPDF.addCell(cell3);
            tablaPDF.addCell(cell4);

            for (int i = 0; i < modelo.getRowCount(); i++) {

                tablaPDF.addCell(modelo.getValueAt(i, 1).toString());
                tablaPDF.addCell(modelo.getValueAt(i, 2).toString());
                tablaPDF.addCell(modelo.getValueAt(i, 3).toString());
                tablaPDF.addCell(modelo.getValueAt(i, 6).toString());
            }

            documento.add(tablaPDF);

            documento.add(new Paragraph(" "));

            // TOTALES
            Paragraph subtotal = new Paragraph(
                    "Subtotal: S/ " + jTextField_Subtotal.getText(),
                    textoFont);

            subtotal.setAlignment(Element.ALIGN_RIGHT);

            Paragraph descuento = new Paragraph(
                    "Descuento: S/ " + jTextField_Descuento.getText(),
                    textoFont);

            descuento.setAlignment(Element.ALIGN_RIGHT);

            Paragraph total = new Paragraph(
                    "Total a pagar: S/ " + jTextField_TotalPagar.getText(),
                    headerFont);

            total.setAlignment(Element.ALIGN_RIGHT);

            Paragraph efectivo = new Paragraph(
                    "Efectivo: S/ " + txt_efectivo.getText(),
                    textoFont);

            efectivo.setAlignment(Element.ALIGN_RIGHT);

            Paragraph cambio = new Paragraph(
                    "Cambio: S/ " + jTextField_Cambio.getText(),
                    textoFont);

            cambio.setAlignment(Element.ALIGN_RIGHT);

            documento.add(subtotal);
            documento.add(descuento);
            documento.add(total);
            documento.add(efectivo);
            documento.add(cambio);

            documento.add(new Paragraph(" "));

            Paragraph gracias = new Paragraph(
                    "Gracias por su compra",
                    headerFont);

            gracias.setAlignment(Element.ALIGN_CENTER);

            documento.add(gracias);

            documento.close();

            JOptionPane.showMessageDialog(this, "Boleta PDF generada correctamente");

            File archivoPDF = new File("Boleta.pdf");

            if (archivoPDF.exists()) {
                Desktop.getDesktop().open(archivoPDF);
            }

            DefaultTableModel modeloLimpiar = (DefaultTableModel) jTable_Venta.getModel();
            modeloLimpiar.setRowCount(0);

            // LIMPIAR CAMPOS
            jTextField_Subtotal.setText("");
            jTextField_Descuento.setText("");
            jTextField_TotalPagar.setText("");
            jTextField_Cambio.setText("");
            txt_efectivo.setText("");
            txt_cantidad_Elegida.setText("");

            // RESETEAR COMBOS
            jComboBox_Clientes.setSelectedIndex(0);
            jComboBox_Productos.setSelectedIndex(0);

            // HABILITAR CLIENTE NUEVAMENTE
            jComboBox_Clientes.setEnabled(true);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error al generar PDF");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_Regis_ventaActionPerformed

    private void jComboBox_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ClientesActionPerformed

    private void jComboBox_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ProductosActionPerformed

    private void jTextField_BuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BuscarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BuscarDNIActionPerformed

    private void jTextField_BuscarDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BuscarDNIKeyTyped

        char c = evt.getKeyChar();
        // Solo números
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números");
        }
        // Máximo 8 dígitos
        if (jTextField_BuscarDNI.getText().length() >= 8) {
            evt.consume();
        }
        // No permitir espacios
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_BuscarDNIKeyTyped

    private void txt_cantidad_ElegidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidad_ElegidaKeyTyped

        char c = evt.getKeyChar();

        // Solo números
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }

        // No permitir espacios
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cantidad_ElegidaKeyTyped

    private void txt_efectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efectivoKeyPressed

    }//GEN-LAST:event_txt_efectivoKeyPressed

    private void txt_efectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efectivoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)
                && c != '.'
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números");
        }

        if (c == '.' && txt_efectivo.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_efectivoKeyTyped

    public void cargarClientes() {

        ArchivoClienteTXT archivo = new ArchivoClienteTXT();
        List<Cliente> lista = archivo.leer();

        jComboBox_Clientes.removeAllItems();

        jComboBox_Clientes.addItem("Seleccione Cliente:");

        for (Cliente c : lista) {

            String cliente = c.getNombre() + " " + c.getApellido();

            jComboBox_Clientes.addItem(cliente);
        }
    }

    public void cargarProductos() {

        ArchivoProductoTXT archivo = new ArchivoProductoTXT();
        List<Producto> lista = archivo.leer();

        jComboBox_Productos.removeAllItems();

        jComboBox_Productos.addItem("Seleccione Producto:");

        for (Producto p : lista) {

            // Si manejas estado y quieres solo activos
            if (p.getEstado() == 1) {

                jComboBox_Productos.addItem(p.getNombre() + " (" + p.getDescripcion() + ")");
            }
        }
    }

    public void calcularTotalVenta() {

        DefaultTableModel modelo = (DefaultTableModel) jTable_Venta.getModel();

        double subtotal = 0;

        for (int i = 0; i < modelo.getRowCount(); i++) {

            subtotal += Double.parseDouble(
                    modelo.getValueAt(i, 6).toString().replace(",", "."));
        }

        double descuento = 0;

        double totalPagar = subtotal - descuento;

        jTextField_Subtotal.setText(
                String.format("%.2f", subtotal).replace(",", "."));

        jTextField_Descuento.setText(
                String.format("%.2f", descuento).replace(",", "."));

        jTextField_TotalPagar.setText(
                String.format("%.2f", totalPagar).replace(",", "."));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AñadirProducto;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Calc_Cambio;
    private javax.swing.JButton jButton_Regis_venta;
    private javax.swing.JComboBox<String> jComboBox_Clientes;
    private javax.swing.JComboBox<String> jComboBox_Productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Venta;
    private javax.swing.JTextField jTextField_BuscarDNI;
    private javax.swing.JTextField jTextField_Cambio;
    private javax.swing.JTextField jTextField_Descuento;
    private javax.swing.JTextField jTextField_Subtotal;
    private javax.swing.JTextField jTextField_TotalPagar;
    private javax.swing.JTextField txt_cantidad_Elegida;
    private javax.swing.JTextField txt_efectivo;
    // End of variables declaration//GEN-END:variables
}
