package Vista;

import Modelo.VentaDAO;
import Clases.Venta;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEBASTIAN GR
 */
public class Registro_Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro_Ventas
     */
    public Registro_Ventas() {
        initComponents();
        this.setSize(new Dimension(800, 700));
        this.setTitle("Registro de Ventas");

        DefaultTableModel modeloInicial = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloInicial.addColumn("ID Venta");
        modeloInicial.addColumn("Cliente");
        modeloInicial.addColumn("Total");
        modeloInicial.addColumn("Fecha");
        jTable_ventas.setModel(modeloInicial);

        jComboBox_Mes.removeAllItems();
        jComboBox_Mes.addItem("Enero");
        jComboBox_Mes.addItem("Febrero");
        jComboBox_Mes.addItem("Marzo");
        jComboBox_Mes.addItem("Abril");
        jComboBox_Mes.addItem("Mayo");
        jComboBox_Mes.addItem("Junio");
        jComboBox_Mes.addItem("Julio");
        jComboBox_Mes.addItem("Agosto");
        jComboBox_Mes.addItem("Septiembre");
        jComboBox_Mes.addItem("Octubre");
        jComboBox_Mes.addItem("Noviembre");
        jComboBox_Mes.addItem("Diciembre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ventas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Mes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton_Exportar_ventas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_GananciaTotal = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE VENTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_ventas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 380));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 750, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Selecciona:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jComboBox_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Mes.addActionListener(this::jComboBox_MesActionPerformed);
        jPanel1.add(jComboBox_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 130, 30));

        jButton_Exportar_ventas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Exportar_ventas.setText("Exportar");
        jButton_Exportar_ventas.addActionListener(this::jButton_Exportar_ventasActionPerformed);
        jPanel1.add(jButton_Exportar_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 120, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ganancia Total:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 585, -1, 40));

        txt_GananciaTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_GananciaTotal.setEnabled(false);
        txt_GananciaTotal.addActionListener(this::txt_GananciaTotalActionPerformed);
        jPanel1.add(txt_GananciaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 592, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 790, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Exportar_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Exportar_ventasActionPerformed
        try {

            if (jTable_ventas.getRowCount() == 0) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "No hay ventas para exportar");

                return;
            }

            String mes = jComboBox_Mes.getSelectedItem().toString();

            Document documento = new Document();

            PdfWriter.getInstance(documento,
                    new FileOutputStream("Reporte_Ventas_" + mes + ".pdf"));

            documento.open();

            // FUENTES
            Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font textoFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);

            // TITULO
            Paragraph titulo = new Paragraph(
                    "REPORTE DE VENTAS - " + mes,
                    tituloFont);

            titulo.setAlignment(Element.ALIGN_CENTER);

            documento.add(titulo);

            documento.add(new Paragraph(" "));

            // TABLA PDF
            PdfPTable tablaPDF = new PdfPTable(4);

            tablaPDF.setWidthPercentage(100);

            tablaPDF.setWidths(new float[]{2, 4, 3, 3});

            // ENCABEZADOS
            PdfPCell c1 = new PdfPCell(new Phrase("ID", headerFont));
            PdfPCell c2 = new PdfPCell(new Phrase("Cliente", headerFont));
            PdfPCell c3 = new PdfPCell(new Phrase("Total", headerFont));
            PdfPCell c4 = new PdfPCell(new Phrase("Fecha", headerFont));

            c1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            c2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            c3.setBackgroundColor(BaseColor.LIGHT_GRAY);
            c4.setBackgroundColor(BaseColor.LIGHT_GRAY);

            tablaPDF.addCell(c1);
            tablaPDF.addCell(c2);
            tablaPDF.addCell(c3);
            tablaPDF.addCell(c4);

            // DATOS DE LA TABLA
            for (int i = 0; i < jTable_ventas.getRowCount(); i++) {

                tablaPDF.addCell(
                        jTable_ventas.getValueAt(i, 0).toString());

                tablaPDF.addCell(
                        jTable_ventas.getValueAt(i, 1).toString());

                tablaPDF.addCell(
                        jTable_ventas.getValueAt(i, 2).toString());

                tablaPDF.addCell(
                        jTable_ventas.getValueAt(i, 3).toString());
            }

            documento.add(tablaPDF);
            documento.add(new Paragraph(" "));

            // GANANCIA TOTAL
            Paragraph ganancia = new Paragraph("Ganancia Total: S/ " + txt_GananciaTotal.getText(), headerFont);
            ganancia.setAlignment(Element.ALIGN_RIGHT);
            documento.add(ganancia);
            documento.close();

            javax.swing.JOptionPane.showMessageDialog(this, "Reporte exportado correctamente");

            // ABRIR PDF
            File archivoPDF = new File("Reporte_Ventas_" + mes + ".pdf");

            if (archivoPDF.exists()) {

                Desktop.getDesktop().open(archivoPDF);
            }

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al exportar reporte");

            e.printStackTrace();
    }//GEN-LAST:event_jButton_Exportar_ventasActionPerformed
    }
    private void txt_GananciaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GananciaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GananciaTotalActionPerformed

    private void jComboBox_MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MesActionPerformed

    }//GEN-LAST:event_jComboBox_MesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mes = jComboBox_Mes.getSelectedItem().toString();

        cargarTablaVentas(mes);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargarTablaVentas(String mesSeleccionado) {

        VentaDAO dao = new VentaDAO();
        List<Venta> lista = dao.listarTodos();

        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("ID Venta");
        modelo.addColumn("Cliente");
        modelo.addColumn("Total");
        modelo.addColumn("Fecha");

        // CORRECCIÓN: BigDecimal para acumulación de totales (2026-06-26 — Auditoría ERP)
        java.math.BigDecimal gananciaTotal = java.math.BigDecimal.ZERO;

        for (Venta v : lista) {

            String fecha = v.getFecha();

            String mes = obtenerMes(fecha);

            if (mes.equalsIgnoreCase(mesSeleccionado)) {

                java.math.BigDecimal total = v.getTotal() != null ? v.getTotal() : java.math.BigDecimal.ZERO;
                Object[] fila = {
                    v.getIdVenta(),
                    v.getCliente(),
                    "S/ " + total.setScale(2, java.math.RoundingMode.HALF_UP).toPlainString(),
                    v.getFecha()
                };

                modelo.addRow(fila);

                gananciaTotal = gananciaTotal.add(total);
            }
        }

        jTable_ventas.setModel(modelo);

        txt_GananciaTotal.setText(gananciaTotal.setScale(2, java.math.RoundingMode.HALF_UP).toPlainString());
    }

    public String obtenerMes(String fecha) {

        String[] partes = fecha.split("/");

        int mes = Integer.parseInt(partes[1]);

        switch (mes) {

            case 1:
                return "Enero";

            case 2:
                return "Febrero";

            case 3:
                return "Marzo";

            case 4:
                return "Abril";

            case 5:
                return "Mayo";

            case 6:
                return "Junio";

            case 7:
                return "Julio";

            case 8:
                return "Agosto";

            case 9:
                return "Septiembre";

            case 10:
                return "Octubre";

            case 11:
                return "Noviembre";

            case 12:
                return "Diciembre";
        }

        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Exportar_ventas;
    private javax.swing.JComboBox<String> jComboBox_Mes;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ventas;
    private javax.swing.JTextField txt_GananciaTotal;
    // End of variables declaration//GEN-END:variables

}
