package Vista;

import Clases.Cliente;
import ArchivosTXT.ArchivoClienteTXT;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ReporteClientes extends javax.swing.JInternalFrame {

    //
    public ReporteClientes() {
        initComponents();
        this.setSize(new Dimension(600, 500));
        this.setTitle("Reporte de Clientes");
        cargarTabla();
    }

    //lee las categorias guardadas en el archivo txt
    public void cargarTabla() {

        ArchivoClienteTXT archivo = new ArchivoClienteTXT();

        List<Cliente> lista = archivo.leer();

        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("ID Cliente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Telefono");
        modelo.addColumn("Estado");

        for (Cliente c : lista) {

            Object[] fila = {
                c.getIdCliente(),
                c.getNombre(),
                c.getApellido(),
                c.getDni(),
                c.getTelefono(),
                c.getEstado() == 1 ? "Activo" : "Inactivo"
            };

            modelo.addRow(fila);
        }

        jTable_CLIENTES.setModel(modelo);
    }

//    private void buscarCategoria() {
//        String buscar = jTextField1.getText().trim();
//
//        if (buscar.isEmpty()) {
//            cargarTabla();
//            return;
//        }
//
//        ArchivoCategoriaTXT archivo = new ArchivoCategoriaTXT();
//        List<Categoria> lista = archivo.leer();
//
//        DefaultTableModel modelo = new DefaultTableModel() {
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//            }
//        };
//
//        modelo.addColumn("ID Categoria");
//        modelo.addColumn("Descripcion");
//        modelo.addColumn("Estado");
//
//        for (Categoria c : lista) {
//            if (c.getDescripcion().toLowerCase().contains(buscar.toLowerCase())) { // Busca categorías cuya descripción contenga el texto escrito, sin importar mayúsculas o minúsculas.
//                Object[] fila = {
//                    c.getIdCategoria(),
//                    c.getDescripcion(),
//                    c.getEstado() == 1 ? "Activo" : "Inactivo"
//                };
//                modelo.addRow(fila);
//            }
//        }
//        // en caso que no se haya encontrado una categoria, muestra un mensaje
//        if (modelo.getRowCount() == 0) {
//            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ninguna categoría");
//        }
//
//        jTable1.setModel(modelo);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane_Clientes = new javax.swing.JScrollPane();
        jTable_CLIENTES = new javax.swing.JTable();
        jButton_Exportar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REPORTE DE CLIENTES");

        jTable_CLIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Clientes.setViewportView(jTable_CLIENTES);

        jButton_Exportar.setText("EXPORTAR");
        jButton_Exportar.addActionListener(this::jButton_ExportarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportarActionPerformed
        try {

            Document documento = new Document();

            PdfWriter.getInstance(documento,
                    new FileOutputStream("ReporteClientes.pdf"));

            documento.open();

            // FUENTES
            Font tituloFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 18);

            Font headerFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 12);

            // TITULO
            Paragraph titulo = new Paragraph(
                    "REPORTE DE CLIENTES",
                    tituloFont);

            titulo.setAlignment(Element.ALIGN_CENTER);

            documento.add(titulo);

            documento.add(new Paragraph(" "));

            // TABLA PDF
            PdfPTable tablaPDF = new PdfPTable(6);

            tablaPDF.setWidthPercentage(100);

            tablaPDF.setWidths(new float[]{2, 4, 4, 3, 3, 3});

            // ENCABEZADOS
            String[] encabezados = {
                "ID",
                "Nombre",
                "Apellido",
                "DNI",
                "Telefono",
                "Estado"
            };

            for (String encabezado : encabezados) {

                PdfPCell cell = new PdfPCell(
                        new Phrase(encabezado, headerFont));

                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);

                tablaPDF.addCell(cell);
            }

            // DATOS
            for (int i = 0; i < jTable_CLIENTES.getRowCount(); i++) {

                for (int j = 0; j < jTable_CLIENTES.getColumnCount(); j++) {

                    tablaPDF.addCell(
                            jTable_CLIENTES.getValueAt(i, j).toString());
                }
            }

            documento.add(tablaPDF);

            documento.close();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "PDF generado correctamente");

            // ABRIR PDF
            File archivoPDF = new File("ReporteClientes.pdf");

            if (archivoPDF.exists()) {

                Desktop.getDesktop().open(archivoPDF);
            }

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al generar PDF");

            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_ExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane_Clientes;
    private javax.swing.JTable jTable_CLIENTES;
    // End of variables declaration//GEN-END:variables
}
