package Vista;

import Clases.Venta;
import Modelo.VentaDAO;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ReporteVentas extends javax.swing.JInternalFrame {

    //
    public ReporteVentas() {
        initComponents();
        this.setSize(new Dimension(600, 500));
        this.setTitle("Reporte de Ventas");
        cargarTabla();
    }

    //lee las categorias guardadas en el archivo txt
    public void cargarTabla() {

        VentaDAO dao = new VentaDAO();

        List<Venta> lista = dao.listarTodos();

        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {

                return false;
            }
        };

        modelo.addColumn("ID Venta");
        modelo.addColumn("Cliente");
        modelo.addColumn("Total");
        modelo.addColumn("Fecha");

        for (Venta v : lista) {

            Object[] fila = {
                v.getIdVenta(),
                v.getCliente(),
                v.getTotal(),
                v.getFecha()
            };

            modelo.addRow(fila);
        }

        jTable_Ventas.setModel(modelo);
    }
//    private void buscarCategoria() {
//        String buscar = jTextField1.getText().trim();
//
//        if (buscar.isEmpty()) {
//            cargarTabla();
//            return;
//        }
//
//        ArchivoCategoriaTXT archivo = new ArchivoCategoriaTXT();
//        List<Categoria> lista = archivo.leer();
//
//        DefaultTableModel modelo = new DefaultTableModel() {
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//            }
//        };
//
//        modelo.addColumn("ID Categoria");
//        modelo.addColumn("Descripcion");
//        modelo.addColumn("Estado");
//
//        for (Categoria c : lista) {
//            if (c.getDescripcion().toLowerCase().contains(buscar.toLowerCase())) { // Busca categorías cuya descripción contenga el texto escrito, sin importar mayúsculas o minúsculas.
//                Object[] fila = {
//                    c.getIdCategoria(),
//                    c.getDescripcion(),
//                    c.getEstado() == 1 ? "Activo" : "Inactivo"
//                };
//                modelo.addRow(fila);
//            }
//        }
//        // en caso que no se haya encontrado una categoria, muestra un mensaje
//        if (modelo.getRowCount() == 0) {
//            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ninguna categoría");
//        }
//
//        jTable1.setModel(modelo);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Ventas = new javax.swing.JTable();
        jButton_Exportar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REPORTE DE VENTAS");

        jTable_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Ventas);

        jButton_Exportar.setText("EXPORTAR");
        jButton_Exportar.addActionListener(this::jButton_ExportarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportarActionPerformed
        try {

            Document documento = new Document();

            PdfWriter.getInstance(documento,
                    new FileOutputStream("ReporteVentas.pdf"));

            documento.open();

            // FUENTES
            Font tituloFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 18);

            Font headerFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 12);

            // TITULO
            Paragraph titulo = new Paragraph(
                    "REPORTE DE VENTAS",
                    tituloFont);

            titulo.setAlignment(Element.ALIGN_CENTER);

            documento.add(titulo);

            documento.add(new Paragraph(" "));

            // TABLA PDF
            PdfPTable tablaPDF = new PdfPTable(4);

            tablaPDF.setWidthPercentage(100);

            tablaPDF.setWidths(new float[]{2, 5, 3, 3});

            // ENCABEZADOS
            PdfPCell cell1 = new PdfPCell(
                    new Phrase("ID Venta", headerFont));

            PdfPCell cell2 = new PdfPCell(
                    new Phrase("Cliente", headerFont));

            PdfPCell cell3 = new PdfPCell(
                    new Phrase("Total", headerFont));

            PdfPCell cell4 = new PdfPCell(
                    new Phrase("Fecha", headerFont));

            cell1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell3.setBackgroundColor(BaseColor.LIGHT_GRAY);
            cell4.setBackgroundColor(BaseColor.LIGHT_GRAY);

            tablaPDF.addCell(cell1);
            tablaPDF.addCell(cell2);
            tablaPDF.addCell(cell3);
            tablaPDF.addCell(cell4);

            // DATOS
            for (int i = 0; i < jTable_Ventas.getRowCount(); i++) {

                tablaPDF.addCell(
                        jTable_Ventas.getValueAt(i, 0).toString());

                tablaPDF.addCell(
                        jTable_Ventas.getValueAt(i, 1).toString());

                tablaPDF.addCell(
                        jTable_Ventas.getValueAt(i, 2).toString());

                tablaPDF.addCell(
                        jTable_Ventas.getValueAt(i, 3).toString());
            }

            documento.add(tablaPDF);

            documento.close();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "PDF generado correctamente");

            // ABRIR PDF
            File archivoPDF = new File("ReporteVentas.pdf");

            if (archivoPDF.exists()) {

                Desktop.getDesktop().open(archivoPDF);
            }

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al generar PDF");

            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_ExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Ventas;
    // End of variables declaration//GEN-END:variables
}
